### ISSUE TITLE
WHERE IS THE MODS AND MY MOD GOT SCRAPPED?!?!

### ISSUE THREAD

**Issue by turipipipip** [TheShovel/penguin-funk#21]
i was gonna play it till i saw no mods. life WTF?!?! PENGUIN FUNK WAS COL WITH MODS AND YOU GIVE THIS SHIT UPTADE?1/ FUCKING THING

**Comment by TheShovel** [comment]
I am sorry but the goal of PenguinFunk is not to host mods on a website, it's to build a stable and easy to use framework that somewhat mimics how PsychEngine works. 
Not gonna lie, seeing this comment makes me kind of sad. Please be nicer next time :(

**Comment by tellmehey** [comment]
bro what
just remake the mods 
- thor, son of odin

**Comment by tellmehey** [comment]
tbh you should have forked the repo to have a legacy ver
 - thor, son of odin

**Comment by turipipipip** [comment]
> I am sorry but the goal of PenguinFunk is not to host mods on a website, it's to build a stable and easy to use framework that somewhat mimics how PsychEngine works. Not gonna lie, seeing this comment makes me kind of sad. Please be nicer next time :(

oh. sorry. sad that you didnt add my mod :(
