### ISSUE TITLE
Permission!

### ISSUE THREAD

**Issue by octigone1** [TheShovel/penguin-funk#7]
Hey, octi here

writing my issue here because i don't know how else to contact you specifically but im here to ask you about permission issues
as far as i am aware, i did not give you explicit permission for you to use my remix in your project. no disrespect it's a neat project but i am uncomfortable with it being used without me being asked. even if you were to ask me, it would have been "no" in the first place.

I can't speak about the others but simply asking for permission first could go a long way, i simply do not feel comfortable with my music being in this and i simply ask for you to pick something else or something different for your menu music.

i also suggest asking for permission next time

thanks in advance

**Comment by TheShovel** [comment]
Hello! I will make sure to replace the song in the next commit. I'll close the issue when I do that (probably in a few hours because its midnight for me)
I'm sorry for not asking for permission! 
I love your music by the way :)

**Comment by TheShovel** [comment]
If you know any mod developers that have their mod here and want it taken down then please tell me!!
This is a little passion project and I dont have easy contact with any of the people who made mods that I have ported over
It just hit me that I should ask for permission for every mod I add, so I am gonna stop adding any new mods until I figure this stuff out. I honestly didnt think that the project would get in the eyes of any of the people I used assets from

**Comment by gomiigg** [comment]
I can ask shyfire if catfight can be used in the mod, not sure about everyone else I don’t have contact with em 

Also a suggestion: try reworking the credits system to appear in game and in the UI. It would help a lot with clearing up some info!

**Comment by TheShovel** [comment]
> I can ask shyfire if catfight can be used in the mod, not sure about everyone else I don’t have contact with em
> 
> Also a suggestion: try reworking the credits system to appear in game and in the UI. It would help a lot with clearing up some info!

Thats a very good idea I will add that

**Comment by gomiigg** [comment]
Looks like ur good with catfight! Just make sure the credits are accurate
(composer, sprite artists, etc.)

**Comment by gomiigg** [comment]
![image](https://github.com/TheShovel/penguin-funk/assets/91437192/3aa07207-ba95-4f45-b35b-d3eafa267749)

**Comment by TheShovel** [comment]
I am currently updating every individual credits .txt file to be formated better so I can properly display the credits in the menu, and a friend of mine is making a custom theme for the menu
This will take a while...

**Comment by TheShovel** [comment]
This has been resolved !
I have updated the song and properly credited every single mod in the freeplay menu instead of just a small text when you enter the level :)

https://github.com/TheShovel/penguin-funk/assets/68913917/96ec79de-546d-493c-8064-6fc94cdb3284
